apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k2r5iqach-nodejs 
  janus-idp.io/tekton: k2r5iqach-nodejs
  backstage.io/kubernetes-id: k2r5iqach-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2r5iqach-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  